<?php

namespace Modules\MachineModel\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\MachineModel\Entities\MachineModel;

class MachineModelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $models = [
            [
                'title_en' => '910',
                'title_ar' => '910',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '916',
                'title_ar' => '916',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '920',
                'title_ar' => '920',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '926',
                'title_ar' => '926',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '930',
                'title_ar' => '930',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '936E',
                'title_ar' => '936E',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '936F',
                'title_ar' => '936F',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '950B',
                'title_ar' => '950B',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '950E',
                'title_ar' => '950E',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '950F',
                'title_ar' => '950F',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '950G',
                'title_ar' => '950G',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '950H',
                'title_ar' => '950H',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '966D',
                'title_ar' => '966D',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '966E',
                'title_ar' => '966E',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '966F',
                'title_ar' => '966F',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '966G',
                'title_ar' => '966G',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '966H',
                'title_ar' => '966H',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '970F',
                'title_ar' => '970F',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '972G',
                'title_ar' => '972G',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '972H',
                'title_ar' => '972H',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '980F',
                'title_ar' => '980F',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '980G',
                'title_ar' => '980G',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '980H',
                'title_ar' => '980H',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '304',
                'title_ar' => '304',
                'category_id' => 1,
                'sub_category_id' => 2,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '305',
                'title_ar' => '305',
                'category_id' => 1,
                'sub_category_id' => 2,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '312B',
                'title_ar' => '312B',
                'category_id' => 1,
                'sub_category_id' => 2,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '312C',
                'title_ar' => '312C',
                'category_id' => 1,
                'sub_category_id' => 2,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '315B',
                'title_ar' => '315B',
                'category_id' => 1,
                'sub_category_id' => 2,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '315C',
                'title_ar' => '315C',
                'category_id' => 1,
                'sub_category_id' => 2,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '320B',
                'title_ar' => '320B',
                'category_id' => 1,
                'sub_category_id' => 2,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '320C',
                'title_ar' => '320C',
                'category_id' => 1,
                'sub_category_id' => 2,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '320E',
                'title_ar' => '320E',
                'category_id' => 1,
                'sub_category_id' => 2,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '320L',
                'title_ar' => '320L',
                'category_id' => 1,
                'sub_category_id' => 2,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '325B',
                'title_ar' => '325B',
                'category_id' => 1,
                'sub_category_id' => 2,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '325C',
                'title_ar' => '325C',
                'category_id' => 1,
                'sub_category_id' => 2,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '325D',
                'title_ar' => '325D',
                'category_id' => 1,
                'sub_category_id' => 2,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '325E',
                'title_ar' => '325E',
                'category_id' => 1,
                'sub_category_id' => 2,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '330B',
                'title_ar' => '330B',
                'category_id' => 1,
                'sub_category_id' => 2,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '330C',
                'title_ar' => '330C',
                'category_id' => 1,
                'sub_category_id' => 2,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '330D',
                'title_ar' => '330D',
                'category_id' => 1,
                'sub_category_id' => 2,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '330E',
                'title_ar' => '330E',
                'category_id' => 1,
                'sub_category_id' => 2,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '330F',
                'title_ar' => '330F',
                'category_id' => 1,
                'sub_category_id' => 2,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '336D',
                'title_ar' => '336D',
                'category_id' => 1,
                'sub_category_id' => 2,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '336E',
                'title_ar' => '336E',
                'category_id' => 1,
                'sub_category_id' => 2,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '336F',
                'title_ar' => '336F',
                'category_id' => 1,
                'sub_category_id' => 2,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '345B',
                'title_ar' => '345B',
                'category_id' => 1,
                'sub_category_id' => 2,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '345C',
                'title_ar' => '345C',
                'category_id' => 1,
                'sub_category_id' => 2,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '345D',
                'title_ar' => '345D',
                'category_id' => 1,
                'sub_category_id' => 2,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '345E',
                'title_ar' => '345E',
                'category_id' => 1,
                'sub_category_id' => 2,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '416B',
                'title_ar' => '416B',
                'category_id' => 1,
                'sub_category_id' => 3,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '416C',
                'title_ar' => '416C',
                'category_id' => 1,
                'sub_category_id' => 3,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '416D',
                'title_ar' => '416D',
                'category_id' => 1,
                'sub_category_id' => 3,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '420C',
                'title_ar' => '420C',
                'category_id' => 1,
                'sub_category_id' => 3,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '420D',
                'title_ar' => '420D',
                'category_id' => 1,
                'sub_category_id' => 3,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '420E',
                'title_ar' => '420E',
                'category_id' => 1,
                'sub_category_id' => 3,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '420F',
                'title_ar' => '420F',
                'category_id' => 1,
                'sub_category_id' => 3,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '426',
                'title_ar' => '426',
                'category_id' => 1,
                'sub_category_id' => 3,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '430D',
                'title_ar' => '430D',
                'category_id' => 1,
                'sub_category_id' => 3,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '430E',
                'title_ar' => '430E',
                'category_id' => 1,
                'sub_category_id' => 3,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '430F',
                'title_ar' => '430F',
                'category_id' => 1,
                'sub_category_id' => 3,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '12G',
                'title_ar' => '12G',
                'category_id' => 1,
                'sub_category_id' => 4,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '14G',
                'title_ar' => '14G',
                'category_id' => 1,
                'sub_category_id' => 4,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '14H',
                'title_ar' => '14H',
                'category_id' => 1,
                'sub_category_id' => 4,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '140G',
                'title_ar' => '140G',
                'category_id' => 1,
                'sub_category_id' => 4,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '140H',
                'title_ar' => '140H',
                'category_id' => 1,
                'sub_category_id' => 4,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '953B',
                'title_ar' => '953B',
                'category_id' => 1,
                'sub_category_id' => 7,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '953C',
                'title_ar' => '953C',
                'category_id' => 1,
                'sub_category_id' => 7,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '953D',
                'title_ar' => '953D',
                'category_id' => 1,
                'sub_category_id' => 7,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '963',
                'title_ar' => '963',
                'category_id' => 1,
                'sub_category_id' => 7,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '973',
                'title_ar' => '973',
                'category_id' => 1,
                'sub_category_id' => 7,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => '421',
                'title_ar' => '421',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 7,
            ],
            [
                'title_en' => '521',
                'title_ar' => '521',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 7,
            ],
            [
                'title_en' => '621',
                'title_ar' => '621',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 7,
            ],
            [
                'title_en' => '721',
                'title_ar' => '721',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 7,
            ],
            [
                'title_en' => 'PC78',
                'title_ar' => 'PC78',
                'category_id' => 1,
                'sub_category_id' => 2,
                'manufacture_id' => 5,
            ],
            [
                'title_en' => 'PC120',
                'title_ar' => 'PC120',
                'category_id' => 1,
                'sub_category_id' => 2,
                'manufacture_id' => 5,
            ],
            [
                'title_en' => 'PC200',
                'title_ar' => 'PC200',
                'category_id' => 1,
                'sub_category_id' => 2,
                'manufacture_id' => 5,
            ],
            [
                'title_en' => 'PC300',
                'title_ar' => 'PC300',
                'category_id' => 1,
                'sub_category_id' => 2,
                'manufacture_id' => 5,
            ],
            [
                'title_en' => 'PC500',
                'title_ar' => 'PC500',
                'category_id' => 1,
                'sub_category_id' => 2,
                'manufacture_id' => 5,
            ],
            [
                'title_en' => 'L30',
                'title_ar' => 'L30',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 3,
            ],
            [
                'title_en' => 'L40',
                'title_ar' => 'L40',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 3,
            ],
            [
                'title_en' => 'L50',
                'title_ar' => 'L50',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 3,
            ],
            [
                'title_en' => 'L70',
                'title_ar' => 'L70',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 3,
            ],
            [
                'title_en' => 'L90',
                'title_ar' => 'L90',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 3,
            ],
            [
                'title_en' => '344',
                'title_ar' => '344',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 2,
            ],
            [
                'title_en' => '65Z',
                'title_ar' => '65Z',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 4,
            ],
            [
                'title_en' => '70Z',
                'title_ar' => '70Z',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 4,
            ],
            [
                'title_en' => '75Z',
                'title_ar' => '75Z',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 4,
            ],
            [
                'title_en' => '90Z',
                'title_ar' => '90Z',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 4,
            ],
            [
                'title_en' => '444',
                'title_ar' => '444',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 2,
            ],
            [
                'title_en' => '544',
                'title_ar' => '544',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 2,
            ],
            [
                'title_en' => '644',
                'title_ar' => '644',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 2,
            ],
            [
                'title_en' => '624H',
                'title_ar' => '624H',
                'category_id' => 1,
                'sub_category_id' => 1,
                'manufacture_id' => 2,
            ],


            [
                'title_en' => '580',
                'title_ar' => '580',
                'category_id' => 1,
                'sub_category_id' => 3,
                'manufacture_id' => 7,
            ],
            [
                'title_en' => '590K',
                'title_ar' => '590K',
                'category_id' => 1,
                'sub_category_id' => 3,
                'manufacture_id' => 7,
            ],
            [
                'title_en' => '590L',
                'title_ar' => '590L',
                'category_id' => 1,
                'sub_category_id' => 3,
                'manufacture_id' => 7,
            ],
            [
                'title_en' => '590M',
                'title_ar' => '590M',
                'category_id' => 1,
                'sub_category_id' => 3,
                'manufacture_id' => 7,
            ],
            [
                'title_en' => '590SM',
                'title_ar' => '590SM',
                'category_id' => 1,
                'sub_category_id' => 3,
                'manufacture_id' => 7,
            ],
            [
                'title_en' => '590N',
                'title_ar' => '590N',
                'category_id' => 1,
                'sub_category_id' => 3,
                'manufacture_id' => 7,
            ],
            [
                'title_en' => '590SN',
                'title_ar' => '590SN',
                'category_id' => 1,
                'sub_category_id' => 3,
                'manufacture_id' => 7,
            ],


            [
                'title_en' => '310D',
                'title_ar' => '310D',
                'category_id' => 1,
                'sub_category_id' => 3,
                'manufacture_id' => 2,
            ],
            [
                'title_en' => '310E',
                'title_ar' => '310E',
                'category_id' => 1,
                'sub_category_id' => 3,
                'manufacture_id' => 2,
            ],
            [
                'title_en' => '310J',
                'title_ar' => '310J',
                'category_id' => 1,
                'sub_category_id' => 3,
                'manufacture_id' => 2,
            ],
            [
                'title_en' => '310G',
                'title_ar' => '310G',
                'category_id' => 1,
                'sub_category_id' => 3,
                'manufacture_id' => 2,
            ],
            [
                'title_en' => '410',
                'title_ar' => '410',
                'category_id' => 1,
                'sub_category_id' => 3,
                'manufacture_id' => 2,
            ],
            [
                'title_en' => 'SD100',
                'title_ar' => 'SD100',
                'category_id' => 1,
                'sub_category_id' => 5,
                'manufacture_id' => 2,
            ],
            [
                'title_en' => 'D4G',
                'title_ar' => 'D4G',
                'category_id' => 1,
                'sub_category_id' => 9,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => 'D9R',
                'title_ar' => 'D9R',
                'category_id' => 1,
                'sub_category_id' => 9,
                'manufacture_id' => 1,
            ],
            [
                'title_en' => 'D10R',
                'title_ar' => 'D10R',
                'category_id' => 1,
                'sub_category_id' => 9,
                'manufacture_id' => 1,
            ],
       ];

       foreach ($models as $model) {
           MachineModel::create($model);
       }
    }
}
